### ISSUE TITLE
字段长度限制无效，content内容仍然显示markdown标记符

### ISSUE THREAD

**Issue by clark874** [Zuoqiu-Yingyi/widget-query#10]
如题，修改如下，但字段长度限制无效，没有换行
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/86122040/155006509-139b3e40-d5d9-40f4-808d-9e509048899c.png">
content内容部分已经显示成功，因此目前就是字段长度限制和换行的问题。
谢谢作者！

**Comment by Zuoqiu-Yingyi** [comment]
@clark874 我这里字段长度限制没有问题?👀
使用长度限制后会将换行替换为空格

**Comment by clark874** [comment]
感谢作者回复，原来重启一下软件可以更新设置。
