### ISSUE TITLE
挂件块自定义属性删除后，需重启后才能生效

### ISSUE THREAD

**Issue by whuwangyong** [Zuoqiu-Yingyi/widget-query#13]
按照下面说明给挂件块添加属性：
> 例如, 如果想要自定义查询结果字段列表, 可以设置自定义块属性 query-fields: ["hpath", "type", "markdown"], 在该块中将会替换 config.query.fields 字段
确实生效了。

然后删除该属性，无效。重启思源后生效。

**Comment by Zuoqiu-Yingyi** [comment]
@whuwangyong 删除后需要重新加载挂件才能生效, 可以使用快捷键 <kbd>F5</kdb> 刷新当前文档或者删除后重新插入挂件

**Comment by whuwangyong** [comment]
> @whuwangyong 删除后需要重新加载挂件才能生效, 可以使用快捷键 F5 刷新当前文档或者删除后重新插入挂件

get！

**Comment by Zuoqiu-Yingyi** [comment]
@whuwangyong 我的主题 [Dark+](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus) 有个使用 <kbd>Ctrl + 单击</kbd> 挂件/iframe 块后可以重新加载该块的功能, 如果想用在其他主题中可以将 `theme.js` 复制到其他主题的目录下即可

**Comment by whuwangyong** [comment]
@Zuoqiu-Yingyi 好！感谢！
