### ISSUE TITLE
在列表中使用可能会造成思源本体系统运行时错误

### ISSUE THREAD

**Issue by leolee9086** [Zuoqiu-Yingyi/widget-query#2]
向前插入时可能需要判定插入位置的合法性

**Comment by leolee9086** [comment]
https://github.com/leolee9086/cc-template/blob/main/index.html 可能可以参考此处119行

**Comment by Zuoqiu-Yingyi** [comment]
@leolee9086 已修复
[fix: 修复列表项中插入查询代码块运行时异常 | Fixed a run-time exception for inserting a …](https://github.com/Zuoqiu-Yingyi/widget-query/commit/248e3644d3bf562fea1ae4d668aea45bdbf76982)
[fix: 修复引述块或超级快中插入查询代码时异常 | Fixed an exception when inserting query co…](https://github.com/Zuoqiu-Yingyi/widget-query/commit/da36028a51c2ce551be0d506b63ad4b1145e6499)

**Comment by Zuoqiu-Yingyi** [comment]
@all-contributors please add @leolee9086  for bug
