### ISSUE TITLE
请教一下如何显示自定义的属性~

### ISSUE THREAD

**Issue by 1995hanjian** [Zuoqiu-Yingyi/widget-query#27]
想请教一下，可以支持自定义属性的查询吗，比如我给某个块增加了"birthday"的属性，在思源里实际属性是"custom-birthday"。

然后我在 query 挂件块的 query-fields 里写入["hpath", "type","custom-birthday"]，query按钮变成红色，表格没有更新。

**Comment by Zuoqiu-Yingyi** [comment]
@1995hanjian 自定义属性(或者说, 所有块属性)都是放置在 `spans` 表中, 使用 `SELECT * FROM blocks ...` 只能通过 IAL(内联属性表)进行字符串匹配查询块属性, 详情请参考 [思源数据库表与字段 · 语雀](https://www.yuque.com/siyuannote/docs/go7uom)

**Comment by 1995hanjian** [comment]
> @1995hanjian 自定义属性(或者说, 所有块属性)都是放置在 `spans` 表中, 使用 `SELECT * FROM blocks ...` 只能通过 IAL(内联属性表)进行字符串匹配查询块属性, 详情请参考 [思源数据库表与字段 · 语雀](https://www.yuque.com/siyuannote/docs/go7uom)

我可以理解为，自定义属性只能显示在IAL里面吗~

**Comment by 1995hanjian** [comment]
> @1995hanjian 或者使用 `attributes` 表进行查询, 该表中 `name` 与 `value` 字段分别对应一个属性的属性名与属性值, 因此自定义属性也在这个表中查询

好的嗷，多谢多谢
