### ISSUE TITLE
更改config.js中的显示字段无效

### ISSUE THREAD

**Issue by clark874** [Zuoqiu-Yingyi/widget-query#28]
如题，更改后仍然显示默认字段，通过用data/widgets/custom.js 覆盖的方式也不能显示自定义字段。
请作者关注，谢谢！

**Comment by Zuoqiu-Yingyi** [comment]
@clark874 请问 *默认字段* 是指 `config.query.fields` 嘛, 请检查更改后是否进行了 *禁用浏览器缓存后刷新* 操作

**Comment by clark874** [comment]
是这个默认字段。
请问“禁用浏览器缓存后刷新操作”如何实现呢？
谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月4日(周一) 凌晨1:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zuoqiu-Yingyi/widget-query] 更改config.js中的显示字段无效 (Issue #28)




 
@clark874 请问 默认字段 是指 config.query.fields 嘛, 请检查更改后是否进行了 禁用浏览器缓存后刷新 操作

**Comment by Zuoqiu-Yingyi** [comment]
@clark874 
![image](https://user-images.githubusercontent.com/49649786/161512473-c0b442f5-97ad-4890-9049-8b98c9be4eb4.png)
