### ISSUE TITLE
怎么显示自定义属性啊

### ISSUE THREAD

**Issue by lmmxj** [Zuoqiu-Yingyi/widget-query#29]
把自定义属性名作为一列这样的，比如id,content,custom-aa,custom-bb

**Comment by lmmxj** [comment]
麻烦写个示例吧，另外自定义属性可能不是每条数据都有，能显示所有数据吗

**Comment by Zuoqiu-Yingyi** [comment]
> 麻烦写个示例吧，另外自定义属性可能不是每条数据都有，能显示所有数据吗

![image](https://user-images.githubusercontent.com/49649786/162559319-00ccef85-c56b-4706-b98e-fd6f9b4d9876.png)
下个版本我试试能不能自动处理

**Comment by Zuoqiu-Yingyi** [comment]
@lmmxj [[思源笔记经验分享] 使用 Query 挂件实现属性视图 - 链滴](https://ld246.com/article/1649526670055)

**Comment by lmmxj** [comment]
IAL 渲染为多列：不能用query-fields的方式选择ial里的字段，只要不为空都会列出

自定义查询: 没有任何自定义属性的文件，会显示不出来。
attributes as a INNER JOIN blocks as b on a.block_id = b.id ​
不能 right join





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zuoqiu-Yingyi/widget-query"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 凌晨1:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zuoqiu-Yingyi/widget-query] 怎么显示自定义属性啊 (Issue #29)





 
@lmmxj [思源笔记经验分享] 使用 Query 挂件实现属性视图 - 链滴

**Comment by Zuoqiu-Yingyi** [comment]
> IAL 渲染为多列：不能用query-fields的方式选择ial里的字段，只要不为空都会列出
> 
> 自定义查询: 没有任何自定义属性的文件，会显示不出来。
> attributes as a INNER JOIN blocks as b on a.block_id = b.id ​
> 不能 right join

了解，那我再用一个新字段控制 ial 渲染吧🙂

**Comment by lmmxj** [comment]
个人感觉最好是 能弄个类似临时表的方式，把自定义属性追加到 blocks里，这样能改显示的字段名。最好是可以直接在查询的页面修改自定义属性那种。
九炎之前做的属性面板有这个功能，但是那个版本被他修改后，也找不到自定义属性了，旧版又被我删了。
当然，能实现查询功能就可以满足大部分需要了。














------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zuoqiu-Yingyi/widget-query"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zuoqiu-Yingyi/widget-query] 怎么显示自定义属性啊 (Issue #29)





  
IAL 渲染为多列：不能用query-fields的方式选择ial里的字段，只要不为空都会列出
 
自定义查询: 没有任何自定义属性的文件，会显示不出来。
 attributes as a INNER JOIN blocks as b on a.block_id = b.id ​
 不能 right join
  
了解，那我再用一个新字段控制 ial 渲染吧🙂

**Comment by Zuoqiu-Yingyi** [comment]
> 个人感觉最好是 能弄个类似临时表的方式，把自定义属性追加到 blocks里，这样能改显示的字段名。最好是可以直接在查询的页面修改自定义属性那种。 九炎之前做的属性面板有这个功能，但是那个版本被他修改后，也找不到自定义属性了，旧版又被我删了。 当然，能实现查询功能就可以满足大部分需要了。

思源提供的数据库 API 只能查询, 不支持增删改~
不过刚刚我在配置中设置了三个配置选项
- `config.query.render.ial.fields.forced`: (Array) 强制渲染的 IAL 字段(优先级最高)
- `config.query.render.ial.fields.ignore`: (Array) IAL 字段渲染黑名单(优先级次高)
- `config.query.render.ial.fields.valid`: (Array) IAL 字段渲染白名单(优先级最低)

配合块自定义属性可以覆盖, 例如设置如下自定义块属性会强制渲染 `name` 与 `alias`
`query-render-ial-fields-forced`: `['name', 'alias']`

**Comment by Zuoqiu-Yingyi** [comment]
@all-contributors please add @lmmxj for ideas
