### ISSUE TITLE
修改正则表达式不起作用

### ISSUE THREAD

**Issue by Danielypzhang** [Zuoqiu-Yingyi/widget-query#3]
感谢这么好的挂件。修改正则表达式为 /^\s*SELECT\s.\s FROM\s+blocks.*/i，任何语句都可以符合。比如想查特定的值比如select markdown，created 原设定不符合正则表达式，返回的格式很乱。修改正则后发现不起作用。另外markdown 无序列表显示不正确显示为 * ddd

**Comment by Zuoqiu-Yingyi** [comment]
@Danielypzhang 
1. 想要更改匹配正则的查询结果显示字段可以更改 `config.query.fields` 中的内容
2. 由于列表是块级元素而非行级元素，所以在表格中无法渲染
