### ISSUE TITLE
建议：查询不到结果的情况下，将上一次的查询结果清空

### ISSUE THREAD

**Issue by o-ut-man** [Zuoqiu-Yingyi/widget-query#33]
比如：
第一次查询，查询成功，底下显示查询到的数据，
然后改变查询条件，进行第二次查询，没有符合条件的数据
虽然查询按钮的颜色有标识，但底下还是会显示第一次查询的结果，容易混淆不直观。

建议在查询不到结果的情况下，将上一次的查询结果清空

**Comment by Zuoqiu-Yingyi** [comment]
主要是查询结果为空的话 API 接口返回的也是一个空列表，没有本次查询的字段名，因此新表格头也没法生成，只能保留上一次的查询结果
