### ISSUE TITLE
展示长内容的优化

### ISSUE THREAD

**Issue by canzj** [Zuoqiu-Yingyi/widget-query#35]
使用场景是 query 得到 content 很长。现状是这一大串内容被放在同一行，导致查看不方便（需要水平滚动）。希望可以设定成自动换行，且能够设定单元格的最大宽度，以优化查看长内容的体验。

**Comment by Zuoqiu-Yingyi** [comment]
该需求目前有两种解决方案:
1. 为查询结果表格设置的块属性不会被覆盖, 可以使用自定义块属性将表格设置为自动换行
2. 参考 `data/widgets/Query/src/script/module/config.js`, 设置 `config.query.style.column`, 通过 `{: style="width: 512px"}` 形式的列级别 IAL 设置列样式
