### ISSUE TITLE
查询结果表格不是按指定的字段先后顺序显示

### ISSUE THREAD

**Issue by entps** [Zuoqiu-Yingyi/widget-query#36]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/125341841/222894628-0e39b245-5e2b-4459-9f96-6d87aed82e67.png">

**Comment by Zuoqiu-Yingyi** [comment]
在字段别名首添加 `__<数字>__` 即可定义查询结果顺序, 如下所示

```sql
SELECT
  content as __01__文件名,
  hpath as __02__笔记本,
  created as __03__创建日期,
  updated as __04__更新日期
FROM
  blocks
WHERE
  type = 'd';
```
