### ISSUE TITLE
能否把不符合正则的表达式，字段也渲染下。另外使用select created markedown 返回的结果顺序不是按照写的顺序来的。

### ISSUE THREAD

**Issue by Danielypzhang** [Zuoqiu-Yingyi/widget-query#6]
自己改了config js, 实现渲染
 default: {
            handler: (row, key) => {
            switch (key)
                    {
                        case 'markdown':

                            switch (config.query.limit) {
                                case 'len':
                                    return markdown2span(cutString(ReplaceSpace(row.markdown, config.query.space), config.query.maxlen));
                                case 'row':
                                    return markdown2span(ReplaceCRLF(cutString(row.markdown, undefined, config.query.maxrow), config.query.CRLF));
                                default:
                                    return markdown2span(row.markdown);
                                };

                        case 'created':

                            return timestampFormat(row.created);

                        case 'updated':
                            return timestampFormat(row.updated);
                        case 'type':
                            return `((${row.id} "${config.query.map.blocktype[row.type]}"))`;
                        case 'hpath':
                            return `((${row.root_id} "${row.hpath}"))`;
                        case 'id':
                            return `((${row.id} "${row.id}"))`;
                        case 'parent_id':
                            if (isEmptyString(row.parent_id)) return '';
                            else return `((${row.parent_id} "${row.parent_id}"))`;
                        case 'root_id':
                            return `((${row.root_id} "${row.root_id}"))`;

                        case 'hash':
                            return `\`${row.hash}\``;

                        case 'box':
                            return `\`${row.box}\``;

                        case 'path':
                            return `\`${row.path}\``;

                        case 'name':
                            return markdown2span(row.name);

                        case 'alias':
                            return markdown2span(row.alias);

                        case 'memo':
                            return markdown2span(row.memo);

                        case 'length':
                            return row.length;

                        case 'subtype':
                            return config.query.map.subtype[row.subtype];

                        case 'ial':
                            let ial = ialParser(row.ial);
                            let ial_markdown = [];
                            for (let key of Object.keys(ial)) {
                                switch (key) {
                                    case 'id':
                                    case 'updated':
                                        continue;
                                    case 'icon':
                                        ial_markdown.push(`\`${key}\`\: :${ial[key].replace(/\.\w+$/, '')}:`);
                                        break;
                                    default:
                                        ial_markdown.push(`\`${key}\`\: \`${ial[key]}\``);
                                        break;
                                }
                            }
                            return ial_markdown.join(config.query.CRLF);

                        case 'sort':
                            return row.sort;

                        default:
                            return `\`${row[key]}\``;

                        }// 其他查询结果默认处理方法, row 是查询结果的一条记录, key 是字段名

                        },

**Comment by Zuoqiu-Yingyi** [comment]
@Danielypzhang 
- 不符合正则的请自定义配置, 因为其他朋友可能会使用字段别名, 无法规范
- 因为 API 接口返回的是 `json` 对象, 所以在不解析 SQL 语句的条件下无法保持顺序不变
