### ISSUE TITLE
【手机伺服】重启软件之后挂件失效

### ISSUE THREAD

**Issue by Tlonglan** [Zuoqiu-Yingyi/widget-query#7]
### 如题，安卓端伺服时，挂件会失效，图标刷新网页之后可以加载，但是查询功能仍然失效

![image](https://user-images.githubusercontent.com/38731172/154403037-ea4a1403-482f-40df-8225-a601d1b60170.png)

--- 

![image](https://user-images.githubusercontent.com/38731172/154403544-06cc94e7-1ad5-478c-8721-49e3a3c52006.png)

**Comment by Zuoqiu-Yingyi** [comment]
思源挂件机制的bug，建议先使用替代方案：使用iframe块，资源为 `widgets/Query`

**Comment by Tlonglan** [comment]
噢噢这样子~
顺便问一下，挂件在手机端是不生效的吗？只能在电脑端使用？

**Comment by Zuoqiu-Yingyi** [comment]
@Tlonglan 近期 D 大应该能解决, 请关注 [将挂件的 `src` 与 `data-src` 属性由完整超链接更换为伺服根路径的绝对路径 · Issue #4206 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/4206)
